title: Jupyter Files for Statistical Thermodynamics: An Information Theory Approach
email: caubin@fordham.edu
description: >- # this means to ignore newlines until "baseurl:"
  This site will host the Jupyter notebooks to go with the
  textbook.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

timezone: America/New_York

# Build settings
theme: minima

header_pages:
  - files.markdown

collections:
  - files

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
