title:  Jupyter Files for Statistical Thermodynamics
email: caubin@fordham.edu
description: >- # this means to ignore newlines until "baseurl:"
  This site will host the Jupyter notebooks to go with 
  the textbook

timezone: America/New_York

# Build settings
theme: jekyll-theme-modernist

header_pages:
   - probability.markdown

# exclude:
#   - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
